---
- name: Running Terraform with S3 backend configuration
  terraform:
    project_path: "{{ app_dir }}/stack/"
    binary_path: "{{ custom_terraform_binary_path | default(omit)}}"
    lock: true
    lock_timeout: 10
    force_init: yes
    backend_config:
      address: "{{ consul_backend_server_address }}"
      scheme: "{{ consul_backend_server_scheme }}"
      path: "{{ consul_backend_kv_path }}"
    state: "{{ tf_action }}"
    workspace: "{{ tf_workspace }}"
    purge_workspace: "{{ (tf_action == 'absent') | ternary('yes','no') }}"
    variables_file: "{{ app_dir }}/environments/{{ tf_environment }}.tfvars"
    variables:
      application: "{{ tf_application }}"
      environment: "{{ tf_environment }}"
    targets: "{{ target_resource_name | default(omit) }}"
    plan_file: "{{ (tf_action == 'planned') | ternary(plan_file_path,omit) }}"
  register: output
